apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: wordpressdb
    software: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpressdb
  template:
    metadata:
      name: mysqldb-pod
      labels:
        app: wordpressdb
    spec:
      containers:
        - image: mysql:5.7
          name: mysqldb
          ports:
            - name: http
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: wpdb
            - name: MYSQL_USER
              value: wpuser
            - name: MYSQL_ROOT_PASSWORD
              value: Parayil@12345
            - name: MYSQL_PASSWORD
              value: Parayil123
----
apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  type: NodePort
  selector:
    app: wordpressweb
  ports:
    - port: 80
      targetPort: 80
